fundscalculator/fundscalculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('funds.urls', namespace='funds')),
]

myshop/cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.conf.urls import url
from . import views


app_name = 'coupons'
urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = i18n_patterns(

    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    url('login/', auth_views.LoginView.as_view(), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # change password urls
    url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),   
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.conf.urls import url
from . import views


app_name = 'orders'
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

skmwork-shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/cart/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from coupons.models import Coupon
from shop.models import Product
from decimal import Decimal


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='carts', on_delete=models.CASCADE, null=True,
                             blank=True)
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)
    is_active = models.BooleanField(default=True)
    is_ordered = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon,
                               related_name='carts',
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Cart')
        verbose_name_plural = _('Cart')

    def __str__(self):
        return 'Cart {}'.format(self.id)

    @property
    def active_items_count(self):
        return self.active_items.count()

    @property
    def is_empty(self):
        return self.active_items_count == 0

    @property
    def active_items(self):
        return self.items.filter(is_deleted=False)

    @property
    def total_price_after_discount(self):
        return self.total_price - self.total_discount

    @property
    def total_discount(self):
        return self.total_price * (self.discount / Decimal('100')) if self.coupon else 0

    @property
    def total_price(self):
        return sum(item.total_cost for item in self.active_items.all())

    @property
    def discount(self):
        return self.coupon.discount if self.coupon and self.coupon.is_valid else 0


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='cart_items', on_delete=models.CASCADE)
    price = models.DecimalField(_('Price'), max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(_('Quantity'), default=1)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)
    is_active = models.BooleanField(default=True)
    is_ordered = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.id)

    @property
    def total_cost(self):
        return self.price * self.quantity

    class Meta:
        verbose_name = _('Cart item')
        verbose_name_plural = _('Cart items')

myshop/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from cart.session_cart import get_cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from .models import Cart, CartItem


@require_POST
def cart_add(request, product_id):
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data

    quantity = cd['quantity']
    update_quantity = cd['update']
    product = get_object_or_404(Product, id=product_id)
    cart = get_cart(request)

    if not cart.id:
        cart.save()

    try:
        cart_item = cart.items.get(product_id=product)
    except CartItem.DoesNotExist:
        cart_item = None

    if cart_item is None:
        cart_item = CartItem(product_id=product.id, quantity=quantity, cart=cart, price=product.price)
    elif cart_item.is_deleted:
        cart_item.quantity = quantity
        cart_item.is_deleted = False
    elif update_quantity:
        cart_item.quantity = quantity
    else:
        cart_item.quantity += quantity
    cart_item.save()

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    get_cart(request).items.filter(product_id=get_object_or_404(Product, id=product_id).id, is_deleted=False) \
        .update(is_deleted=True)
    return redirect('cart:cart_detail')


def cart_detail(request):
    return render(request,
                  'cart/detail.html',
                  {'cart': get_cart(request),
                   'coupon_apply_form': CouponApplyForm(),
                   })

myshop/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
	{% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
{% if not cart.is_empty %}
<div class="row">
    <div class="col-12">
        <h3>{% trans "Your shopping cart" %}</h3>
    </div>
</div>
<div class="row">
    <div class="col-12 col-xs-6 col-md-6 col-lg-8">
        {% for item in cart.active_items %}
        <div class="row mt-3">
            {% with product=item.product %}
            <div class="col-6 col-xs-6 col-md-6 col-lg-2">
                {% load thumbnail %}
                {% thumbnail product.image "150" as im %}
                <a class="card-img-hover" href="{{ product.get_absolute_url }}"><img class="d-block w-100" src="{{ im.url }}"></a>
                {% endthumbnail %}
            </div>
            <div class="col-5 col-xs-5 col-md-5 col-lg-9">
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-12 col-lg-4">
                        <a href="{{ product.get_absolute_url }}"><p class="text">{{ product.name }}</p></a>
                    </div>
                    <div class="col-12 col-xs-12 col-md-12 col-lg-4">
                        <p class="text">{{ item.price }} ₽ * {{ item.quantity }}</p>
                    </div>
                    <div class="col-12 col-xs-12 col-md-12 col-lg-4">
                        <p class="text">{{ item.total_cost }} ₽</p>
                    </div>
                </div>
            </div>
            <div class="col-1 col-xs-1 col-md-1 col-lg-1">
                <a type="button" class="close" aria-label="Close" href="{% url 'cart:cart_remove' product.id %}">
                    <span aria-hidden="true">&times;</span>
                </a>
            </div>
            {% endwith %}
        </div>
        {% endfor %}
    </div>
    <div class="col-12 col-xs-6 col-md-6 col-lg-4 mt-2">
        <div class="card">
            <div class="card-body">
                {% if cart.coupon %}
                <div class="col-12 mt-2 ">
                    <div class="d-flex">
                        <div class="p">{% trans "Subtotal" %}:</div>
                        <div class="p ml-auto">{{ cart.total_price }} ₽</div>
                    </div>
                </div>
                <div class="col-12 mt-2 ">
                    {% with code=cart.coupon.code discount=cart.coupon.discount %}
                    <div class="d-flex">
                        <div class="p">{% trans "Discount" %} ({{ discount }}% ("{{ code }}"):</div>
                        <div class="p ml-auto">-{{ cart.total_discount|floatformat:"2" }} ₽</div>
                    </div>
                    {% endwith %}
                </div>
                {% endif %}
                <div class="col-12 mt-2 ">
                    <div class="d-flex">
                        <div class="p">{% trans "Total" %}:</div>
                        <div class="p ml-auto">{{ cart.total_price_after_discount|floatformat:"2" }} ₽</div>
                    </div>
                </div>
                <div class="col-12 mt-2 mb-2">
                    <div class="p">
                        <a href="{% url 'orders:order_create' %}" class='btn btn-lg btn-block btn-primary'>
                            {% trans "Checkout" %}
                        </a>
                    </div>
                </div>
                <div class="col-12 mt-4">
                    <div class="p">
                        <form class="form" action="{% url 'coupons:apply' %}" method="post">
                            <div class="input-group">
                                {{ coupon_apply_form }}
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit">{% trans 'Apply' %}</button>
                                </div>
                            </div>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h3>{% trans "Your cart is empty" %}</h3>
    {% endif %}
    {% endblock %}
</div>