fundscalculator/fundscalculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('funds.urls', namespace='funds')),
]

myshop/cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = i18n_patterns(

    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    url('login/', auth_views.LoginView.as_view(), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # change password urls
    url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),   
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from . import views
from django.conf.urls import url
from django.urls import reverse, reverse_lazy


app_name = 'shop'
urlpatterns = [
    # alternative way to include authentication views
    # path('', include('django.contrib.auth.urls')),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),

]

skmwork-shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from modeltranslation.translator import translator, TranslationOptions


class Category(models.Model):
    name = models.CharField(_('Category name'), max_length=200, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(_('Product name'), max_length=200, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=200, db_index=True)
    image = models.ImageField(_('Image'), upload_to='media/products/%Y/%m/%d', blank=True)
    description = models.TextField(_('Description'), blank=True)
    price = models.DecimalField(_('Price'), max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(_('Stock'))
    available = models.BooleanField(_('Available'), default=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('shop:product_detail',
                       args=[self.category.slug, self.slug])

myshop/shop/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, Page
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products_list = Product.objects.filter(available=True).order_by('category')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products_list})


def product_detail(request, category_slug, slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(Product,
                                category_id=category.id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   })

myshop/shop/templates/shop/product/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class='row'>
    <div class='col-12 col-xs-8 col-md-8 col-lg-5'>
        <div class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    {% load thumbnail %}
                    {% thumbnail product.image "300" as im %}
                    <img src="{{ im.url }}" class="d-block w-100">
                    {% endthumbnail %}
                </div>
            </div>
        </div>
    </div>
    <div class='col-12 col-xs-4 col-md-4 col-lg-7 mt-2'>

        <h5>{{ product.name }}</h5>
        <a href="{{ product.category.get_absolute_url }}"><p class="text-muted">{{ product.category }}</p></a>
        <p class="price">{{ product.price }} ₽</p>
        <p>{{ product.description|linebreaks }}</p>
        <form class="form" action="{% url 'cart:cart_add' product.id %}" method="post">
            <div class="form-group row">
                <div class="col-12 col-xs-8 col-md-6 col-lg-6">
                    {{ cart_product_form | crispy }}
                    {% csrf_token %}
                </div>
            </div>
            <button type='submit' class='btn btn-primary'>{% trans 'Add to cart' %}</button>
        </form>
    </div>
</div>
    </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}{% trans "Products" %}{% endif %}
{% endblock %}
{% block content %}

<div class="nav-scroller py-1 mb-2 sticky-top bg-white">
    <nav class="nav d-flex">
        <a class="p-2 {% if category %} text-muted{% else %} text-dark font-weight-bold{% endif %}" href="{% url 'shop:product_list' %}">{% trans "All" %}</a>
        {% for c in categories %}
        <a class="p-2 {% if category.slug != c.slug %} text-muted{% else %} text-dark font-weight-bold{% endif %}" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        {% endfor %}
    </nav>
</div>
<div class="row">
    <div class="col-12 col-sm-12 col-md-10 col-lg-10">
        <div class="row">
            {% for product in products %}
            <div class="col-12 col-sm-4 col-md-4 col-lg-4">
                <div class="card border-0">
                    {% load thumbnail %}
                    {% thumbnail product.image "300" as im %}
                    <a class="card-img-hover" href="{{ product.get_absolute_url }}">
                        <img class="card-img-top" src="{{ im.url }}" alt="{{ product.name }}">
                    </a>
                    {% endthumbnail %}
                    <br>
                    <div class="card-body">
                        <div class="card-title"><a href="{{ product.get_absolute_url }}"><h5>{{ product.name }}</h5></a></div>
                        <p></p>
                        <small class="text-muted">{{ product.price }} ₽</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}