fundscalculator/fundscalculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('funds.urls', namespace='funds')),
]

myshop/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse, reverse_lazy

app_name = 'accounts'

urlpatterns = [
    # previous login view
    # path('login/', views.user_login, name='login'),

    # alternative way to include authentication views
    # path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
]

myshop/cart/urls.py
from django.conf.urls import url
from . import views


app_name = 'cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = i18n_patterns(

    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    url('login/', auth_views.LoginView.as_view(), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # change password urls
    url('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    url('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),   
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from . import views
from django.conf.urls import url
from django.urls import reverse, reverse_lazy


app_name = 'shop'
urlpatterns = [
    # alternative way to include authentication views
    # path('', include('django.contrib.auth.urls')),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),

]

skmwork-shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path('grappelli/', include('grappelli.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from modeltranslation.translator import translator, TranslationOptions


class Category(models.Model):
    name = models.CharField(_('Category name'), max_length=200, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(_('Product name'), max_length=200, db_index=True)
    slug = models.SlugField(_('Slug'), max_length=200, db_index=True)
    image = models.ImageField(_('Image'), upload_to='media/products/%Y/%m/%d', blank=True)
    description = models.TextField(_('Description'), blank=True)
    price = models.DecimalField(_('Price'), max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(_('Stock'))
    available = models.BooleanField(_('Available'), default=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('shop:product_detail',
                       args=[self.category.slug, self.slug])

myshop/shop/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage, Page
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products_list = Product.objects.filter(available=True).order_by('category')
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products_list})


def product_detail(request, category_slug, slug):
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(Product,
                                category_id=category.id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   })

myshop/shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>
        {% block title %}{% trans "My shop" %}{% endblock %}
    </title>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static '/css/sticky-footer-navbar.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>
<body>
{% include 'shop/navbar.html' %}
      <div class='container'>
        {% if messages %}
      <div class="alert alert-success messages">
          {% for message in messages %}
          <span>{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
          {% endfor %}
      </div>
      {% endif %}
      {% block content %}{% endblock %}
    </div>
<form id="csrf_token">{% csrf_token %}</form>
</main>
<script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static '/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/js/scripts.js' %}"></script>
</body>
</html>

myshop/shop/templates/shop/navbar.html
{% url 'shop:product_list' as home_url %}
{% url 'shop:product_list' as product_list_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:edit' as account_url %}
{% url 'cart:cart_detail' as cart_url %}
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    {% trans "My shop" %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'shop:product_list' %}">{% trans "Products" %}</a>
      </li>
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}">{% trans "Cart" %}{% if cart|length > 0 %}<span class="badge badge-pill badge-danger">{{ cart|length }}</span>{% endif %}</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
         {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}

        {% for language in languages %}
              {% if language.code != LANGUAGE_CODE %}
            <li class="nav-item">
              <a class="nav-link" href="/{{ language.code }}/">{{ language.code|capfirst  }}</a>
            </li>
              {% endif %}
        {% endfor %}
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == account_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:edit' %}">{% trans "User" %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == register_url %}active{% endif %}"><a class="nav-link" href="{% url 'accounts:register' %}">
        <span class="glyphicon glyphicon-user"></span>{% trans "Registration" %}</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>{% trans "Log-in" %}</a>
      </li>

      {% endif %}

    </ul>
  </div>
</div>
</nav>